# Generated by Django 3.1.3 on 2020-12-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bestellung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellung', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.kunde')),
            ],
        ),
    ]
